name: CI

env:
  NODE_VERSION: lts/*

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
      - run: pnpm install --frozen-lockfile
      - run: pnpm check
      - run: pnpm lint

  npm-publish-dry-run-and-upload-pkg-pr-now:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm nlx pkg-pr-new publish
