name: CI

env:
  NODE_VERSION: lts/*

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
      - run: pnpm install --frozen-lockfile
      - run: pnpm check
      - run: pnpm lint

  npm-publish-dry-run-and-upload-pkg-pr-now:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm nlx pkg-pr-new publish
